version = "3.11.5"
runner.dialect = scala3
maxColumn = 120

# Equivalent to rewrite.scala3.preset = common, introduced after 3.11.5.
rewrite.scala3 {
  convertToNewSyntax = true
  newSyntax.deprecated = false
  endMarker.remove.blankGaps.min = 1
  optionalBraces {
    enabled = true
    insert.blankGaps.min = 1
    remove.blankGaps.max = 0
  }
}
